<div class="cms_home_block">
<div class="cms_home_block_top">
<div class="imgpanel">
<a href="http://52.55.237.50/caricraft/home-decor.html/">
<img title="Home Decor" src='<?php echo $this->getViewFileUrl('Aheadworks_Rbslider::images/homedecor.jpg'); ?>'  alt="Home Decor" width="380" height="284" />
</a>
<span>Home decor</span>
<p>A beautifully finished set of 4, these are sure to make for an exciting tropical accent ...</p>
</div>
<div class="imgpanel">
<a href="http://52.55.237.50/caricraft/clothing.html/">
<img title="Cloth" src='<?php echo $this->getViewFileUrl('Aheadworks_Rbslider::images/clothing.jpg'); ?>' alt="Cloth" width="380" height="284" />
</a> 
<span>Cloth</span>
<p>Proclaim your Barbadian identity with a cool flag top. This baby doll top ...</p>
</div>
<div class="imgpanel">
<a href="http://52.55.237.50/caricraft/food.html/">
<img title="Famous Food" src='<?php echo $this->getViewFileUrl('Aheadworks_Rbslider::images/food.jpg'); ?>'  alt="Food" width="380" height="284" />
</a>
<span>Food</span>
<p>Savour this unique taste of the Caribbean. Rose & Laflamme - Sweet and Dandy ...</p>
</div>
</div>
<div class="cms_home_block_bottom">
<div class="arrival_block_left">
<div class="arrivetext">
<div class="arrivetext_inn">
<h2>New Arrivals</h2>
<p>Duis lacinia sodales odio in pharetra. Morbi ac magna luctus, suscipit velit.</p>
<a class="shopbtn" title="New Products" href="new-products" target="_self">Shop Now</a>
</div>
</div>
</div>
<div class="offer_block_right">
<div class="offer_text">
<span>Get</span>
<h2>20% off</h2>
<span class="patt_bott">On Selected Books</span>
<a class="shopbtn" href="http://52.55.237.50/caricraft/deals.html/">Shop Now</a>
</div>
</div>
</div>
</div>
<div class="home-blog">
<h3>Latest Blog</h3>
<div class="block-content">
<ol class="items">
<li class="item">
<img class="blog__post-featured-image" src="http://52.55.237.50/caricraft/pub/media/blog/demo_new-4.jpg">
<div class="post-details">
<h4>Lorem ipsum dolor sit amet, consectetur</h4>
<a href="http://52.55.237.50/caricraft/blog/test-4.html">Read more</a>
</div>
</li>
<li class="item">
<img class="blog__post-featured-image" src="http://52.55.237.50/caricraft/pub/media/blog/demo_new-3.jpg">
<div class="post-details">
<h4>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h4>
<a href="http://52.55.237.50/caricraft/blog/test-3.html">Read more</a>
</div>
</li>
<li class="item">
<img class="blog__post-featured-image" src="http://52.55.237.50/caricraft/pub/media/blog/demo_new-2.jpg">
<div class="post-details">
<h4>Lorem ipsum dolor sit amet, consectetur</h4>
<a href="http://52.55.237.50/caricraft/blog/test-2.html">Read more</a>
</div>
</li>
<li class="item">
<img class="blog__post-featured-image" src="http://52.55.237.50/caricraft/pub/media/blog/demo_new-1.jpg">
<div class="post-details">
<h4>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h4>
<a href="http://52.55.237.50/caricraft/blog/test-1.html">Read more</a>
</div>
</li>
</ol>
</div>
</div>
